spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: def_kitchen_route
          uri: http://localhost:8070
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Powered-By, FreddysAPIGateway
          predicates:
            - Path=/kitchen/**
        - id: def_order_route
          uri: http://localhost:8060
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Powered-By, FreddysAPIGateway
          predicates:
            - Method=GET,POST
            - Path=/order/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG